<?php

class ArticlePage extends Page{

    private static $can_be_root = false ;  // for disabling articalPage as root menu on admin

    private static $db = [
        'Date' =>'Date',
        'Teaser'=>'Text',
        'Author'=>'Varchar',
];

    public function getCMSFields()
    {
        $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub
        $fields->addFieldToTab('Root.Content.Main', DateField::create('Date','Date Of Articale')->setConfig('showcalendar',true),'Content');
        $fields->addFieldToTab('Root.Main', TextareaField::create('Teaser'),'Content') ;
        $fields->addFieldToTab('Root.Main', TextField::create('Author','Author Name'),'Content') ;
        return $fields;
    }

}

class ArticlePage_Controller extends Page_Controller{

}

